portfolio-project/pages/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

portfolio-project/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

portfolio-project/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls'), name='portfolio'),
    path('polls/', include('polls.urls'), name='polls'),
    path('tictactoe/', include('tictactoe.urls'), name='tictactoe'),
]
urlpatterns += staticfiles_urlpatterns()

portfolio-project/tictactoe/urls.py
from django.urls import path

from . import views

app_name = 'tictactoe'
urlpatterns = [
    path("", views.index, name="index"),
]

portfolio-project/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

portfolio-project/tictactoe/models.py
from django.db import models

# Create your models here.

portfolio-project/pages/forms.py
from django import forms
from django.core.mail import send_mail

class ContactForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput
                            (attrs={'class':'form-control',
				                    'id':'name',
                                    'placeholder': 'Name'}))
    email = forms.EmailField(required=True, widget=forms.TextInput
                            (attrs={'class':'form-control',
                                    'id':'email',
                                    'placeholder': 'Email'}))
    subject = forms.CharField(required=False, widget=forms.TextInput
                             (attrs={'class':'form-control',
                                     'id':'subject',
                                     'placeholder': 'Subject'}))
    message = forms.CharField(required=True, widget=forms.Textarea
                             (attrs={'class':'form-control',
                                     'id':'message',
                                     'placeholder': 'Message',
                                     'cols': 30,
                                     'rows': 8}))

portfolio-project/pages/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.core.mail import send_mail, BadHeaderError
from django.views import View
from django.conf import settings
import logging

from .forms import ContactForm

# Create your views here.# Create your views here.
class IndexView(View):
    template_name = 'pages/index.html'
    success_url = 'home' # dummy view
    context = {}
    # myform is the definition/class of your form which contains all attrs.

    def get(self, request):
        self.context['form'] = ContactForm() # fill out your data here for get request
        return render(request, self.template_name, self.context)

    def post(self, request):
        # create a variable to keep track of the form
        messageSent = False

        form = ContactForm(request.POST)
        # Form Validation
        print(form.errors)
        if form.is_valid():
            cd = form.cleaned_data
            subject = "Sending an email with Django"
            name = cd['name']
            email = cd['email']
            subject = cd['subject']
            message = 'name: '+name+'\n'
            message += 'From: '+email+'\n'

            message += cd['message']
            #perform any logical validations here and save the form if required
            send_mail(subject, message, email, ['chris.polanco2@gmail.com'])

            messageSent = True

        context = self.context
        context['form'] = form # just to show you that you can access that form anywhere
        context['messageSent'] = messageSent
        return render(request, self.template_name, context)

def successView(request):
    return HttpResponse('Success! Thank you for your message.')

portfolio-project/polls/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        # TODO: Look into F() for concurrency issues
        # https://docs.djangoproject.com/en/3.2/ref/models/expressions/#avoiding-race-conditions-using-f
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

portfolio-project/tictactoe/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse

# Create your views here.# Create your views here.
def index(response):
    return render(response, 'tictactoe/index.html', {})

portfolio-project/pages/templates/base.html
{% load static %}

<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>My Portfolio</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="#page-top">My Portfolio</a>
            <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#portfolio">Projects</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#about">About</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#resume">Resume</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Masthead-->
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">
            <!-- Masthead Avatar Image-->
            <img class="mb-5 rounded-circle" src="{% static 'img/_M2_9020.jpg' %}" width='250px' height='250px' />
            <!-- Masthead Heading-->
            <h1 class="masthead-heading text-uppercase mb-0">Chris Polanco</h1>
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Masthead Subheading-->
            <p class="masthead-subheading font-weight-light mb-0">Software Engineer</p>
        </div>
    </header>
    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>

portfolio-project/pages/templates/pages/contact.html
<section class="page-section contact" id="contact">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                <h2 class="heading-section">Get in touch with me</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-10 col-md-12">
                <div class="wrapper">
                    <div class="row justify-content-center">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="dbox w-100 text-center">
                                    <div class="icon d-flex align-items-center justify-content-center">
                                        <span class="fa fa-paper-plane"></span>
                                    </div>
                                    <div class="text">
                                        <p><span>Email:</span> <a href="mailto:chris.polanco2@gmail.com">chris.polanco2@gmail.com</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="contact-wrap">
                                {% if messageSent %}
                                <div class="container">
                                    <div class="row text-center">
                                        <div class="col-md-12">
                                            <h3><strong>Email successfully sent</strong></h3>
                                            <p>Your message was successfully sent to {{ form.cleaned_data.to }}</p>
                                        </div>
                                    </div>
                                </div>
                                {% else %}
                                <form method="POST" id="contactForm" name="contactForm" class="contactForm">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                {{ form.name }}
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                {{ form.email }}
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                {{ form.subject }}
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                {{ form.message }}
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group form-actions">
                                                <input type="submit" value="Send Message" class="btn btn-primary">
                                                <div class="submitting"></div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

portfolio-project/pages/templates/pages/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Masthead-->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="mb-5 rounded-circle" src="{% static 'img/_M2_9020.jpg' %}" width='250px' height='250px' />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Chris Polanco</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-0">Software Engineer</p>
    </div>
</header>

{% include "pages/resume.html" %}
{% include "pages/contact.html" %}
{% endblock %}

portfolio-project/pages/templates/pages/resume.html
<section class="page-section resume" id="resume">
    <div class="container">
        <div class="section-title">
            <center>
                <h2>Resume</h2>
                <hr />
                <br />
            </center>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <h3 class="resume-title">Sumary</h3>
                <div class="resume-item pb-0">
                    <h4>Chris Polanco</h4>
                    <p><em>Innovative and deadline-driven Graphic Designer with 3+ years of experience designing and developing user-centered digital/print marketing material from initial concept to final, polished deliverable.</em></p>
                    <ul>
                        <li>Miramar, FL</li>
                        <li>chris.polanco2@gmail.com</li>
                    </ul>
                </div>

                <h3 class="resume-title">Education</h3>
                <div class="resume-item">
                    <h4>Master of Science &amp; Software Engineer</h4>
                    <h5>Graduated, 2017</h5>
                    <p><em>University of Scranton, Scranton, PA</em></p>
                </div>
                <div class="resume-item">
                    <h4>Bachelor of Science &amp; Computer Science</h4>
                    <h5>Graduated, 2014</h5>
                    <p><em>University of Scranton, Scranton, PA</em></p>
                </div>
            </div>
            <div class="col-lg-6">
                <h3 class="resume-title">Professional Experience</h3>
                <div class="resume-item">
                    <h4>Software Engineer</h4>
                    <h5>October 2017 - January 2021</h5>
                    <p><em>Jack Henry & Associates, Remote</em></p>
                    <ul>
                        <li>Use HTML, CSS, JavaScript and PowerOn to create and modify software for Credit Unions.</li>
                        <li>Experience using Symitar-based technologies including SymForm, Goodnight processing, SymXchange.</li>
                        <li>Work with clients remotely from different time zones</li>
                        <li>Side Project - Created software with Python to automate the process of creating product folders and renaming files in our version control system.</li>
                    </ul>
                </div>
                <div class="resume-item">
                    <h4>Programmer</h4>
                    <h5>July 2015 - April 2017</h5>
                    <p><em>Valor Credit Union, Scranton, PA</em></p>
                    <ul>
                        <li>Created and managed all programs for the Credit Union as a sole programmer.</li>
                        <li>
                            Automated Wire Transfers – worked with employees to figure out steps for creating wire
                            transfers and created a program to automate steps including the creation of a form with member and bank information.
                        </li>
                        <li>Created my own questionnaire system to verify members, bringing us to code with NCUA.</li>
                        <li>Worked directly with Pentagon Federal Credit Union during the merge process to help move members and numbers from our system to theirs.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

portfolio-project/polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block content %}
<section class="page-section polls-detail bg-secondary" id="polls-detail">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Poll Details</h1>
                <hr />
                <br />
            </div>
        </div>
        <div class="row">
            <div class="col-md-auto bg-primary">
                <form action="{% url 'polls:vote' question.id %}" method="POST">
                    <!-- Handle Cross Site Request Forgeries -->
                    {% csrf_token %}
                    <fieldset>
                        <legend>
                            <h1>{{ question.question_text }}</h1>
                        </legend>
                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                        <div class='wrapper text-center'>
                            <div class="btn-group-vertical">
                                {% for choice in question.choice_set.all %}
                                <input width=100% type="radio" class="btn-check" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" autocomplete=" off" />
                                <label class="btn btn-secondary" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                                {% endfor %}
                            </div>
                        </div>
                    </fieldset>
                    <br />
                    <input class="btn btn-primary" type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

portfolio-project/polls/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}

<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Polls</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-0">Simple Polls app to keep track of polls and votes</p>
    </div>
</header>
<section class="page-section bg-secondary text-white text-center" id="polls">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>My Polls</h1>
                <hr />
                <br />
            </div>
        </div>
        <div class="row">
            {% if latest_question_list %}
            {% for question in latest_question_list %}
            <div class="col-md-4">
                <h1>{{ question.question_text }}</h1>
                <a href="{% url 'polls:detail' question.id %}"><button class="btn btn-primary">Vote</button></a>
            </div>
            {% endfor %}
            {% else %}
            <div class="col-md-12">
                <p>No polls are available.</p>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

portfolio-project/polls/templates/polls/results.html
{% extends 'base.html' %}

{% block content %}
<section class="page-section polls-results bg-secondary" id="polls-results">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Poll Results</h1>
                <hr />
                <br />
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 bg-primary">
                <h1>{{ question.question_text }}</h1>

                <ul class="list-group">
                    {% for choice in question.choice_set.all %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        {{ choice.choice_text }}
                        <span class="badge badge-primary badge-pill">{{ choice.votes }}</span>
                    </li>
                    {% endfor %}
                </ul>
                <br />
                <a href="{% url 'polls:detail' question.id %}"><button class="btn btn-primary">Vote again?</button></a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

portfolio-project/templates/base.html
{% load static %}
<!doctype html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>My Portfolio</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'pages:index' %}">My Portfolio</a>
            <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'tictactoe:index' %}">TicTacToe</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'pages:index' %}#projects">Projects</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'pages:index' %}#about">About</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'pages:index' %}#resume">Resume</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'pages:index' %}#contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>

portfolio-project/tictactoe/templates/tictactoe/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Masthead-->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Tic Tac Toe</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-0">Tic Tac Toe Game Playable with Friends</p>
    </div>
</header>

<!-- playboard section -->
<div class="play-board">
    <div class="play-area">
        <section>
            <span class="box1"></span>
            <span class="box2"></span>
            <span class="box3"></span>
        </section>
        <section>
            <span class="box4"></span>
            <span class="box5"></span>
            <span class="box6"></span>
        </section>
        <section>
            <span class="box7"></span>
            <span class="box8"></span>
            <span class="box9"></span>
        </section>
    </div>
</div>

<!-- <script src="script.js"></script> -->
{% endblock %}